import { useLayoutEffect, useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Auth } from "aws-amplify";
import { useSelector } from "react-redux";
import { RootState } from "../../redux/store";

export default function Preview() {
  const { userId, docId } = useParams();
  const navigate = useNavigate();

  const isAuthenticated = useSelector((state: RootState) => state.user.isAuthenticated);
  const [doc, setDoc] = useState<any>(null);
  const [presignedUrl, setPresignedUrl] = useState<string | null>(null);
  const [summary, setSummary] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!isAuthenticated) {
      navigate("/");
    }
  }, [isAuthenticated, navigate]);

  useLayoutEffect(() => {
    const docData = localStorage.getItem("previewDoc");

    if (!docData) {
      console.warn("No previewDoc found in localStorage.");
      navigate(`/Account/${userId}/Documents`);
      return;
    }

    try {
      const parsed = JSON.parse(docData);
      if (!parsed.document_id || parsed.document_id !== docId) {
        console.warn("Mismatch between docId in URL and localStorage.");
        navigate(`/Account/${userId}/Documents`);
        return;
      }

      setDoc(parsed);
      fetchPresignedUrl(parsed);
    } catch (err) {
      console.error("Failed to parse previewDoc:", err);
      navigate(`/Account/${userId}/Documents`);
    }
  }, [userId, docId, navigate]);

  useEffect(() => {
    return () => {
      localStorage.removeItem("previewDoc");
    };
  }, []);

  const fetchPresignedUrl = async (doc: any) => {
    try {
      const session = await Auth.currentSession();
      const token = session.getIdToken().getJwtToken();

      const response = await fetch(
        `https://p0hzjm73nl.execute-api.us-east-1.amazonaws.com/prod/presigned-url?key=${doc.s3_key}`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      const { url } = await response.json();
      setPresignedUrl(url);
    } catch (err) {
      console.error("Failed to fetch presigned URL:", err);
    }
  };

  const handleSummarize = () => {
    setLoading(true);
    setTimeout(() => {
      setSummary(
        "This is a summary generated by ChatGPT based on the content of the document. It highlights the main points, topics, and important data."
      );
      setLoading(false);
    }, 2000);
  };

  const renderPreview = () => {
    if (!presignedUrl || !doc) return <p>Loading preview...</p>;

    const extension = doc.file_name.split(".").pop().toLowerCase();
    if (["pdf"].includes(extension)) {
      return (
        <iframe
          title="PDF Preview"
          src={presignedUrl}
          style={{ width: "100%", height: "100%", border: "none" }}
        ></iframe>
      );
    } else if (["jpg", "jpeg", "png"].includes(extension)) {
      return <img src={presignedUrl} alt="Preview" style={{ maxWidth: "100%" }} />;
    } else {
      return (
        <iframe
          title="Text Preview"
          src={presignedUrl}
          style={{ width: "100%", height: "100%", border: "none" }}
        ></iframe>
      );
    }
  };

  return (
    <div className="container py-4">
      <div className="mb-3">
        <button
          type="button"
          className="btn btn-outline-secondary"
          onClick={() => navigate(-1)}
        >
          &larr; Go Back
        </button>
      </div>
      <div className="row">
        {/* Document Viewer */}
        <div className="col-md-8">
          <h4 className="mb-3">Document Preview</h4>
          <div className="border rounded p-3 bg-light" style={{ minHeight: "400px" }}>
            {renderPreview()}
          </div>
        </div>

        {/* GPT Summary Panel */}
        <div className="col-md-4">
          <h5 className="mb-3">AI Assistant</h5>
          <button
            type="button"
            className="btn btn-outline-success mb-3"
            onClick={handleSummarize}
            disabled={loading}
          >
            {loading ? (
              <>
                <span
                  className="spinner-border spinner-border-sm text-success me-2"
                  role="status"
                  aria-hidden="true"
                ></span>
                Summarizing...
              </>
            ) : (
              "Summarize by GPT"
            )}
          </button>
          <div className="border rounded p-3 bg-white" style={{ minHeight: "300px" }}>
            {summary ? (
              <p>{summary}</p>
            ) : (
              <p className="text-muted">Click the button to generate a summary of the document.</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
